services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/oma?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: oma
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  springapimysql-net:
    driver: bridge

volumes:
  db_data:
